/**
 * **Micro game 2: the moon.** Gate v3, batch 1, delivered without back-and-forth.
 *
 * > *"Eu quero que você crie para mim um astronauta. Quero ser capaz de pular e andar em todas
 * > as direções com ele. O ambiente: o solo lunar, similar a vista da lua com a terra ao
 * > fundo."*
 *
 * **Three things in the sentence the engine could not do this morning**, and each is now a
 * mechanism rather than a special case:
 *
 * | the ask | what it needed |
 * |---|---|
 * | *andar em todas as direções* | `src/core/yaw.ts` — a body turned about its own axis, eight facings from one grammar |
 * | *pular* | gravity and a height in the runtime, and a ground shadow, which is the only thing that makes a jump readable from above |
 * | *o solo lunar* | a floor a player can walk **into**, which means his paint order follows him |
 *
 * **The moon is where this scene's own rules come from, and two of them are inversions of
 * everything the forest taught.**
 *
 * - **`haze` is zero.** Every other scene expresses distance as aerial perspective. There is
 *   no air here, so a distant crater is exactly as sharp and as dark as a near one, and depth
 *   is carried by the floor and by overlap alone. The knob does not go away; it goes to zero,
 *   which is the difference between a mechanism and a habit.
 * - **The sky is the darkest thing and the ground is the brightest.** In the forest the sky
 *   was the light the trees stood against. Here the ground is sunlit rock and the sky is
 *   vacuum, so every silhouette reads the other way up.
 * - **The Earth does not move.** The moon is tidally locked: from a landing site the Earth
 *   hangs in one place, forever. It gets no drift, no bob and no cadence — and that stillness,
 *   next to three clouds that never stopped moving in the forest, is the loudest thing here.
 */
import type { Scene } from '../scene/compose.ts'

/** Dark to light. The lit strip along the horizon is the sun catching the far regolith. */
const REGOLITH: readonly [number, number, number][] = [
  [30, 28, 27],
  [48, 45, 42],
  [74, 70, 64],
  [104, 99, 90],
]

/**
 * **Six planes, and the near four are a floor the player walks across.**
 *
 * The rule from 15/08 still binds: every gap between two planes must exceed what anything
 * standing on them overhangs. A boulder overhangs 2 px and a crater is authored around its own
 * centre; these are 12 to 22 px apart.
 */
const FAR = 0.94
const MID = 0.66
const NEAR = 0.34
const FRONT = 0.08

export const moonScene: Scene = {
  name: 'moon',
  w: 320,
  h: 188,
  frames: 24,
  msPerFrame: 50,
  scale: 3,
  // The horizon sits high, because on the moon it is close: the body is small and the surface
  // curves away within a couple of kilometres. A low horizon would read as a desert.
  ground: 96,
  nearRow: 182,
  // **Zero, and it is the whole point.** No atmosphere, no aerial perspective.
  haze: 0,
  // Vacuum. Not black — a pure black sky reads as a hole in the monitor rather than as space,
  // and the outline ink is already darker than this.
  sky: [7, 7, 13],
  stars: { count: 90, colors: [[120, 126, 150], [186, 192, 214], [238, 242, 252]], seed: 23, below: 96 },
  groundRamp: REGOLITH,
  placements: [
    // **The Earth, hanging.** Placed by `y` and marked `sky`, so it takes no ground haze and
    // is drawn before everything: it is not far away, it is *behind the world*.
    { grammar: 'earth', tunables: 'earth', x: 236, y: 40, sky: true },

    // The far rim: craters at the horizon, where the surface curves out of sight.
    { grammar: 'crater-c', tunables: 'regolith', x: 60, depth: FAR },
    { grammar: 'crater-a', tunables: 'regolith', x: 196, depth: FAR },
    { grammar: 'rock-c', tunables: 'regolith', x: 128, depth: FAR },
    { grammar: 'rock-a', tunables: 'regolith', x: 288, depth: FAR },

    { grammar: 'crater-b', tunables: 'regolith', x: 26, depth: MID },
    { grammar: 'crater-c', tunables: 'regolith', x: 174, depth: MID },
    { grammar: 'rock-b', tunables: 'regolith', x: 106, depth: MID },
    { grammar: 'rock-c', tunables: 'regolith', x: 252, depth: MID },

    { grammar: 'crater-a', tunables: 'regolith', x: 88, depth: NEAR },
    { grammar: 'rock-c', tunables: 'regolith', x: 210, depth: NEAR },
    { grammar: 'rock-a', tunables: 'regolith', x: 300, depth: NEAR },

    { grammar: 'crater-b', tunables: 'regolith', x: 150, depth: FRONT },
    { grammar: 'rock-b', tunables: 'regolith', x: 40, depth: FRONT },
    { grammar: 'rock-c', tunables: 'regolith', x: 272, depth: FRONT },

    /**
     * **The astronaut**, and every clip name here is a *family*: the runtime appends the
     * compass point and reaches `lope-e`, `lope-ne`, `lope-n` and their mirrors. Fifteen
     * grammars, all of them generated by yawing one authored body.
     */
    {
      grammar: 'astro-idle-e', tunables: 'astronaut', x: 150, depth: 0.42, anchor: 'foot',
      clips: {
        'idle-e': { grammar: 'astro-idle-e', tunables: 'astronaut' },
        'idle-ne': { grammar: 'astro-idle-ne', tunables: 'astronaut' },
        'idle-n': { grammar: 'astro-idle-n', tunables: 'astronaut' },
        'idle-se': { grammar: 'astro-idle-se', tunables: 'astronaut' },
        'idle-s': { grammar: 'astro-idle-s', tunables: 'astronaut' },
        'lope-e': { grammar: 'astro-lope-e', tunables: 'astronaut' },
        'lope-ne': { grammar: 'astro-lope-ne', tunables: 'astronaut' },
        'lope-n': { grammar: 'astro-lope-n', tunables: 'astronaut' },
        'lope-se': { grammar: 'astro-lope-se', tunables: 'astronaut' },
        'lope-s': { grammar: 'astro-lope-s', tunables: 'astronaut' },
        'leap-e': { grammar: 'astro-leap-e', tunables: 'astronaut' },
        'leap-ne': { grammar: 'astro-leap-ne', tunables: 'astronaut' },
        'leap-n': { grammar: 'astro-leap-n', tunables: 'astronaut' },
        'leap-se': { grammar: 'astro-leap-se', tunables: 'astronaut' },
        'leap-s': { grammar: 'astro-leap-s', tunables: 'astronaut' },
      },
      player: {
        // 38 px/s. A lope is 12 frames at 85 ms, so he covers 39 px per cycle — one body
        // length, which is the ratio that stops a walk from looking like a skate.
        speed: 38, minX: 18, maxX: 302,
        idle: 'idle', walk: 'lope',
        roam: {
          // He may walk from the middle distance to the front of the stage. Not to the
          // horizon: the sprite does not shrink, and a full-size figure standing on the
          // skyline is the one thing that would break the scale of the whole picture.
          minRow: 128, maxRow: 178,
          // 26 rows/s against 38 px/s across. The floor is foreshortened — a step "into" the
          // picture covers fewer rows than the same step across it — and that single ratio
          // is what makes a flat band read as a plane you are standing on.
          depthSpeed: 26,
        },
        jump: {
          clip: 'leap',
          /**
           * **A sixth of a g, and this is the number the whole commission rests on.**
           *
           * At 320 px across, the astronaut is 46 px for a 1.8 m person, so the scene is
           * about 26 px per metre. Lunar gravity is 1.62 m/s², which is 42 px/s². An impulse
           * of 62 px/s gives an apex of 46 px — one and a half times his own height — and a
           * hang of **2.95 seconds**. On Earth the same push would clear 9 px and be over in
           * 0.6 s.
           *
           * That contrast is the only place in this scene where the moon is something the
           * player *feels* rather than something I drew.
           */
          gravity: 42, impulse: 62,
        },
      },
    },
  ],
}
